
<?php
echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "  <style>\n";
echo "    @import url(https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic);\n";
echo "@import url(//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css);\n";
echo "\n";
echo "    html, body {\n";
echo "  height: 100%;\n";
echo "}\n";
echo "body {\n";
echo "  margin: 0;\n";
echo "  padding: 0;\n";
echo "  /*background: url(https://cdn.pixabay.com/photo/2015/08/08/00/07/graduation-879941_1280.jpg);*/\n";
echo "  font-family: 'Lato', sans-serif;\n";
echo "  -webkit-font-smoothing: antialiased;\n";
echo "}\n";
echo "h1 {\n";
echo "  font-size: 30px;\n";
echo "  line-height: 38px;\n";
echo "  margin: 0;\n";
echo "  position: relative;\n";
echo "  font-weight: 300;\n";
echo "  color: #666;\n";
echo "  text-shadow: 0 1px 1px rgba(#fff,0.6);\n";
echo "}\n";
echo ".form-2 {\n";
echo "    /* Size and position */\n";
echo "    width: 500px;\n";
echo "    margin: 30px auto 30px;\n";
echo "    padding: 10px;\n";
echo "    position: relative;\n";
echo "\n";
echo "    /* Styles */\n";
echo "    background: #fffaf6;\n";
echo "    border-radius: 4px;\n";
echo "    color: #7e7975;\n";
echo "    box-shadow:\n";
echo "        0 2px 2px rgba(0,0,0,0.2),        \n";
echo "        0 1px 5px rgba(0,0,0,0.2),        \n";
echo "        0 0 0 12px rgba(255,255,255,0.4);\n";
echo "}\n";
echo "input {\n";
echo "  box-sizing: border-box;\n";
echo "  font-family: 'Lato', Calibri, Arial, sans-serif;\n";
echo "  font-size: 13px;\n";
echo "  font-weight: 400;\n";
echo "  display: block;\n";
echo "  width: 100%;\n";
echo "  padding: 5px;\n";
echo "  margin-bottom: 5px;\n";
echo "  border: 3px solid #ebe6e2;\n";
echo "  border-radius: 5px;\n";
echo "  transition: all 0.3s ease-out;\n";
echo "}\n";
echo "input:hover{\n";
echo "  border-color: #CCC;\n";
echo "}\n";
echo "input:focus{\n";
echo "  outline: none;\n";
echo "}\n";
echo "label {\n";
echo "  display: block;\n";
echo "  padding: 0 0 5px 2px;\n";
echo "  cursor: pointer;\n";
echo "  text-transform: uppercase;\n";
echo "  font-weight: 400;\n";
echo "  text-shadow: 0 1px 0 rgba(255,255,255,0.8);\n";
echo "  font-size: 11px;\n";
echo "}\n";
echo "table{\n";
echo "  width: 100%;\n";
echo "}\n";
echo "a{\n";
echo "  color: #7e7975;\n";
echo "}\n";
echo "a:link {\n";
echo "    text-decoration: none;\n";
echo "}\n";
echo "\n";
echo "a:visited {\n";
echo "    text-decoration: none;\n";
echo "}\n";
echo "\n";
echo "a:hover {\n";
echo "    text-decoration: underline;\n";
echo "}\n";
echo "\n";
echo "a:active {\n";
echo "    text-decoration: underline;\n";
echo "}\n";
echo "button {\n";
echo "  box-shadow: inset 0 1px rgba(#fff,0.3);\n";
echo "  border-radius: 3px;\n";
echo "  cursor: pointer;\n";
echo "  font-family: 'Lato', Calibri, Arial, sans-serif;\n";
echo "  font-size: 14px;\n";
echo "  line-height: 38px;\n";
echo "  text-align: center;\n";
echo "  font-weight: bold;\n";
echo "  width: 48%;\n";
echo "  position: relative;\n";
echo "  background : linear-gradient(#fbd568, #ffb347);\n";
echo "}\n";
echo "\n";
echo "input[type=\"submit\"] {\n";
echo "  background : linear-gradient(#34a5cf, #2a8ac4);\n";
echo "  border: 1px solid #2b8bc7;\n";
echo "  color: #ffffff;\n";
echo "  text-shadow: 0 -1px rgba(0,0,0,0.3);\n";
echo "  text-decoration: none;\n";
echo "}\n";
echo "  </style>\n";
echo "<body onLoad=\"disableClick()\">\n";
echo "\n";
echo "    <div style=\"text-align:center\"><h2><strong>GPA Calculator</strong> Indonesia</h2></div>\n";
echo "<div class=\"form-2\">\n";
echo "<table>\n";
echo "  <tr>\n";
echo "    <td>Nilai Maksimal</td>\n";
echo "    <td>:</td>\n";
echo "    <td><input type=\"text\" id=\"max\" value=\"10\"></td>\n";
echo "    \n";
echo "  </tr>\n";
echo "  <tr>\n";
echo "  	<td>Nilai Minimal Kelulusan</td>\n";
echo "    <td>:</td>\n";
echo "    <td><input type=\"text\" id=\"min\" value=\"5\"></td>\n";
echo "  </tr>\n";
echo "  <tr>\n";
echo "    <td>Jenjang</td>\n";
echo "    <td>:</td>\n";
echo "    <td>\n";
echo "    <select id=\"jenjang\">\n";
echo "      <option value=\"D1\">D1</option>\n";
echo "      <option value=\"D2\">D2</option>\n";
echo "      <option value=\"D3\">D3</option>\n";
echo "      <option value=\"D4\">D4</option>\n";
echo "      <option value=\"S1\">S1</option>\n";
echo "      <option value=\"Profesi\">Profesi</option>\n";
echo "      <option value=\"S2\">S2</option>\n";
echo "      <option value=\"Spesialis\">Spesialis</option>\n";
echo "      <option value=\"S3\">S3</option>\n";
echo "    </select>\n";
echo "    </td>\n";
echo "  </tr>\n";
echo "</table>\n";
echo "<br><br>\n";
echo "\n";
echo "<table id=\"Table1\">\n";
echo "  <tr>\n";
echo "    <th >Course</th>\n";
echo "    <th >Credit</th> \n";
echo "    <th >Grade</th>\n";
echo "      <th></th>\n";
echo "  </tr>\n";
echo "  <tr>\n";
echo "    <td><input type=\"text\" id=\"course1\" value=\"\"></td>\n";
echo "    <td><input type=\"text\" id=\"credit1\" value=\"\"></td>\n";
echo "    <td><input type=\"text\" id=\"grade1\" value=\"\"></td>\n";
echo "      <td><a href=\"javascript:void(0);\" style=\"font-size: 11px;\" onclick=\"removeRow(this)\">Delete</a></td>\n";
echo "  </tr>\n";
echo "  <tr>\n";
echo "    <td><input type=\"text\" id=\"course2\" value=\"\"></td>\n";
echo "    <td><input type=\"text\" id=\"credit2\" value=\"\"></td>\n";
echo "    <td><input type=\"text\" id=\"grade2\" value=\"\"></td>\n";
echo "      <td><a href=\"javascript:void(0);\" style=\"font-size: 11px;\" onclick=\"removeRow(this)\">Delete</a></td>\n";
echo "  </tr>\n";
echo "  <tr>\n";
echo "    <td><input type=\"text\" id=\"course3\" value=\"\"></td>\n";
echo "    <td><input type=\"text\" id=\"credit3\" value=\"\"></td>\n";
echo "    <td><input type=\"text\" id=\"grade3\" value=\"\"></td>\n";
echo "      <td><a href=\"javascript:void(0);\" style=\"font-size: 11px;\" onclick=\"removeRow(this)\">Delete</a></td>\n";
echo "  </tr>\n";
echo "  <tr>\n";
echo "    <td><input type=\"text\" id=\"course4\" value=\"\"></td>\n";
echo "    <td><input type=\"text\" id=\"credit4\" value=\"\"></td>\n";
echo "    <td><input type=\"text\" id=\"grade4\" value=\"\"></td>\n";
echo "      <td><a href=\"javascript:void(0);\" style=\"font-size: 11px;\" onclick=\"removeRow(this)\">Delete</a></td>\n";
echo "  </tr>\n";
echo "</table>\n";
echo "<table>\n";
echo "  <tr>\n";
echo "    <td>\n";
echo "      <input type=\"submit\" value='Add Course' onclick=\"addRow()\">\n";
echo "    </td>\n";
echo "    <td>\n";
echo "      <input type=\"number\" id=\"sumOfRow\" value=\"\" placeholder=\"Number of rows to add\" max=\"50\" min=\"1\">\n";
echo "    </td>\n";
echo "  </tr>\n";
echo "</table>\n";
echo "<br><br>\n";
echo "\n";
echo "\n";
echo "<div style=\"text-align:center\">\n";
echo "  <button onclick=\"calculateGPA()\">Convert</button>\n";
echo "  <p>Your IPK: <span id=\"convertedIpk\"></span></p>\n";
echo "<p><span id=\"predikatIpk\"></span>\n";
echo "</p>\n";
echo "</div>\n";
echo "</div>\n";
echo "</body>\n";
echo "<script type=\"text/javascript\">\n";
echo "  function p(float) {\n";
echo "    if (float){\n";
echo "      return parseFloat(float)\n";
echo "    }\n";
echo "    return 0\n";
echo "  }\n";
echo "\n";
echo "  function hitungIPK(listSks, listNilai) {\n";
echo "    var totalSksKaliNilai = 0, totalSks = 0;\n";
echo "    for (i = 0; i < listSks.length; i++) {\n";
echo "      sks = listSks[i];\n";
echo "      nilai = listNilai[i];\n";
echo "      totalSksKaliNilai += (sks * nilai);\n";
echo "      totalSks += sks;\n";
echo "    }\n";
echo "    console.log(\"totalSksKaliNilai\", totalSksKaliNilai)\n";
echo "    console.log(\"totalSks\", totalSks)\n";
echo "    var ipk = totalSksKaliNilai / totalSks\n";
echo "    if (totalSks == 0){\n";
echo "        ipk = 0;\n";
echo "    } \n";
echo "    return ipk;\n";
echo "  }\n";
echo "\n";
echo "  function getA2(jenjang) {\n";
echo "    var dua = [\"D1\", \"D2\", \"D3\", \"D4\", \"S1\"];\n";
echo "    var tiga = [\"Profesi\", \"S2\", \"Spesialis\", \"S3\"];\n";
echo "    if (dua.includes(jenjang)) {\n";
echo "      return 2;\n";
echo "    }\n";
echo "    if (tiga.includes(jenjang)) {\n";
echo "      return 3;\n";
echo "    }\n";
echo "    return -1;\n";
echo "  }\n";
echo "\n";
echo "  function getPredikat(GPA, jenjang) {\n";
echo "    console.log(\"nol\", jenjang, GPA)\n";
echo "    var dua = [\"D1\", \"D2\", \"D3\", \"D4\", \"S1\"];\n";
echo "    var tiga = [\"Profesi\", \"S2\", \"Spesialis\", \"S3\"];\n";
echo "    if (dua.includes(jenjang)) {\n";
echo "      console.log(\"satu\", jenjang)\n";
echo "      return getPredikatBachelor(GPA);\n";
echo "    }\n";
echo "    if (tiga.includes(jenjang)) {\n";
echo "      console.log(\"dua\", jenjang)\n";
echo "      return getPredikatMaster(GPA);\n";
echo "    }\n";
echo "    return -1;\n";
echo "  }\n";
echo "\n";
echo "  function getPredikatMaster(GPA) {\n";
echo "    console.log(\"bachelor\", GPA)\n";
echo "    if (GPA >= 3.75 && GPA <=4) {\n";
echo "      return \"CUM LAUDE\";\n";
echo "    }\n";
echo "    if (GPA >= 3.51 && GPA <=3.74) {\n";
echo "      return \"SANGAT MEMUASKAN\";\n";
echo "    }\n";
echo "    if (GPA >= 3 && GPA <= 3.5){\n";
echo "      return \"MEMUASKAN\";\n";
echo "    }\n";
echo "    return \"GAGAL\";\n";
echo "  }\n";
echo "\n";
echo "  function getPredikatBachelor(GPA) {\n";
echo "    console.log(\"master\", GPA)\n";
echo "    if (GPA >= 3.51 && GPA <=4) {\n";
echo "      return \"CUM LAUDE\";\n";
echo "    }\n";
echo "    if (GPA >= 2.76 && GPA <=3.5) {\n";
echo "      return \"SANGAT MEMUASKAN\";\n";
echo "    }\n";
echo "    if (GPA >= 2 && GPA <= 2.75){\n";
echo "      return \"MEMUASKAN\";\n";
echo "    }\n";
echo "    return \"GAGAL\";\n";
echo "  }\n";
echo "\n";
echo "   function convertIPK(ipkLuar, nilaiMax, nilaiMin, jenjang) {\n";
echo "    var a1 = 4, a2 = getA2(jenjang);\n";
echo "    console.log(\"ini dia\", ipkLuar, nilaiMax, nilaiMin, jenjang, a1,a2)\n";
echo "    if (nilaiMax < nilaiMin){\n";
echo "        var tmp = a1;\n";
echo "        a1 = a2;\n";
echo "        a2 = tmp;\n";
echo "        return (((ipkLuar - nilaiMax) * (a1 - a2)) / (nilaiMin - nilaiMax)) + (a2);\n";
echo "    }\n";
echo "    return (((ipkLuar - nilaiMin) * (a1 - a2)) / (nilaiMax - nilaiMin)) + (a2);\n";
echo "  }\n";
echo "\n";
echo "  // function pressButton() {\n";
echo "  //   var listSks = [\n";
echo "  //     p(document.getElementById(\"credit1\").value),\n";
echo "  //     p(document.getElementById(\"credit2\").value),\n";
echo "  //     p(document.getElementById(\"credit3\").value),\n";
echo "  //     p(document.getElementById(\"credit4\").value)\n";
echo "  //   ]\n";
echo "  //   var listNilai = [\n";
echo "  //     p(document.getElementById(\"grade1\").value),\n";
echo "  //     p(document.getElementById(\"grade2\").value),\n";
echo "  //     p(document.getElementById(\"grade3\").value),\n";
echo "  //     p(document.getElementById(\"grade4\").value)\n";
echo "  //   ]\n";
echo "\n";
echo "  //     console.log(listSks, listNilai)\n";
echo "\n";
echo "  //   var jenjang = document.getElementById(\"jenjang\").value\n";
echo "  //   var min = p(document.getElementById(\"min\").value)\n";
echo "  //   var max = p(document.getElementById(\"max\").value)\n";
echo "\n";
echo "  //   var ipk = hitungIPK(listSks, listNilai)\n";
echo "  //   convertedIpk = convertIPK(ipk, max, min, jenjang)\n";
echo "  //   document.getElementById(\"convertedIpk\").innerHTML = convertedIpk.toFixed(2)\n";
echo "  //   console.log(\"ending\", convertedIpk, jenjang)\n";
echo "  //   predikatIpk = getPredikat(convertedIpk, jenjang)\n";
echo "  //   document.getElementById(\"predikatIpk\").innerHTML = predikatIpk\n";
echo "  // }\n";
echo "\n";
echo "  function addRow(){\n";
echo "      var sumOfRow = 1;\n";
echo "      console.log(\"add\", sumOfRow)\n";
echo "      if (document.getElementById(\"sumOfRow\").value){\n";
echo "        console.log(\"msauk\", document.getElementById(\"sumOfRow\"))\n";
echo "        sumOfRow = document.getElementById(\"sumOfRow\").value;\n";
echo "      }\n";
echo "\n";
echo "      for (i = 0; i < sumOfRow; i++) {\n";
echo "        rows()\n";
echo "      }\n";
echo "\n";
echo "      \n";
echo " \n";
echo "      \n";
echo "\n";
echo "  }\n";
echo "\n";
echo "  function rows(){\n";
echo "      document.getElementById(\"sumOfRow\")\n";
echo "      var table = document.getElementById(\"Table1\");\n";
echo "\n";
echo "      var rowCount = table.rows.length;\n";
echo "      var row = table.insertRow(rowCount);\n";
echo "\n";
echo "      var cell1 = row.insertCell(0);\n";
echo "      var element1 = document.createElement(\"input\");\n";
echo "      element1.type = \"text\";\n";
echo "      cell1.appendChild(element1);\n";
echo "\n";
echo "      var cell2 = row.insertCell(1);\n";
echo "      var element2 = document.createElement(\"input\");\n";
echo "      element2.type = \"text\";\n";
echo "      cell2.appendChild(element2);\n";
echo "\n";
echo "      var cell3 = row.insertCell(2);\n";
echo "      var element3 = document.createElement(\"input\");\n";
echo "      element3.type = \"text\";\n";
echo "      cell3.appendChild(element3);\n";
echo "\n";
echo "      var cell4 = row.insertCell(3);\n";
echo "      var element4 = document.createElement(\"a\");\n";
echo "      element4.setAttribute(\"href\", \"javascript:void(0);\");\n";
echo "      element4.onclick = function () { removeRow(this) };\n";
echo "      element4.style.fontSize = \"11px\";\n";
echo "      var linkText = document.createTextNode(\"Delete\");\n";
echo "      element4.appendChild(linkText);\n";
echo "      cell4.appendChild(element4);\n";
echo "  }\n";
echo "\n";
echo "  function removeRow(r) {\n";
echo "      console.log(r)\n";
echo "      var i = r.parentNode.parentNode.rowIndex;\n";
echo "      var tbl = document.getElementById(\"Table1\");\n";
echo "      tbl.deleteRow(i);\n";
echo "  }\n";
echo "\n";
echo "  function calculateGPA(){\n";
echo "      var table = document.getElementById('Table1');\n";
echo "      var rowCount = table.rows.length;\n";
echo "      var allCredits = [];\n";
echo "      var allGrades = [];\n";
echo "\n";
echo "      for (var i = 1; i < rowCount; i++) {\n";
echo "          var credits = p(table.rows[i].cells[1].children[0].value);\n";
echo "          var grades = p(table.rows[i].cells[2].children[0].value);\n";
echo "\n";
echo "          allCredits.push(credits);\n";
echo "          allGrades.push(grades)\n";
echo "      }\n";
echo "\n";
echo "      console.log(allCredits,allGrades);\n";
echo "\n";
echo "      var jenjang = document.getElementById(\"jenjang\").value\n";
echo "      var min = p(document.getElementById(\"min\").value)\n";
echo "      var max = p(document.getElementById(\"max\").value)\n";
echo "\n";
echo "      var ipk = hitungIPK(allCredits, allGrades)\n";
echo "      console.log(\"ipknya ini dia\", ipk)\n";
echo "      convertedIpk = convertIPK(ipk, max, min, jenjang)\n";
echo "      document.getElementById(\"convertedIpk\").innerHTML = convertedIpk.toFixed(2)\n";
echo "      console.log(\"ending\", convertedIpk, jenjang)\n";
echo "      predikatIpk = getPredikat(convertedIpk, jenjang)\n";
echo "      document.getElementById(\"predikatIpk\").innerHTML = predikatIpk\n";
echo "\n";
echo "  }\n";
echo "</script>\n";
echo "</html>\n";
echo "\n";
echo "\n";
?>
